In [1]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

In [2]:
#load the dataset
data = pd.read_csv("seattle-weather.csv")
data

            date  precipitation  temp_max  temp_min  wind  weather
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle
1     2012-01-02           10.9      10.6       2.8   4.5     rain
2     2012-01-03            0.8      11.7       7.2   2.3     rain
3     2012-01-04           20.3      12.2       5.6   4.7     rain
4     2012-01-05            1.3       8.9       2.8   6.1     rain
...          ...            ...       ...       ...   ...      ...
1456  2015-12-27            8.6       4.4       1.7   2.9     rain
1457  2015-12-28            1.5       5.0       1.7   1.3     rain
1458  2015-12-29            0.0       7.2       0.6   2.6      fog
1459  2015-12-30            0.0       5.6      -1.0   3.4      sun
1460  2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]

In [3]:
#apply lable encoder
le=LabelEncoder()
for i in data.columns:
    data[i]=le.fit_transform(data[i])
data

      date  precipitation  temp_max  temp_min  wind  weather
0        0              0        25        30    43        0
1        1             43        21        26    41        2
2        2              3        23        34    19        2
3        3             74        24        31    43        2
4        4              5        18        26    57        2
...    ...            ...       ...       ...   ...      ...
1456  1456             34        10        24    25        2
1457  1457              6        11        24     9        2
1458  1458              0        15        22    22        1
1459  1459              0        12        18    30        4
1460  1460              0        12        14    31        4

[1461 rows x 6 columns]

In [4]:
def train_model(model):
    model.fit(x_train,y_train)
    y_pred = model.predict(x_test)
    print("Accuracy score is : ",accuracy_score(y_test,y_pred)*100)
    print("Confusion matrix : ",confusion_matrix(y_test,y_pred))
    print("Classification report : ",classification_report(y_test,y_pred))
    sns.heatmap(confusion_matrix(y_test,y_pred),annot=True,fmt="d",cmap="YlGnBu",cbar=False,linewidths=0.5,annot_kws={"size":16},yticklabels=["Rainy","Sunny","Cloudy","Windy"],xticklabels=["Rainy","Sunny","Cloudy","Windy"])
    plt.show()

In [5]:
#split data into x and y
x=data.drop(['date','weather'],axis=1)
y=data['weather']
x.shape,y.shape

((1461, 4), (1461,))

In [6]:
#apply train test split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((1168, 4), (293, 4), (1168,), (293,))

In [ ]:
model=[LogisticRegression(max_iter=1000),SVC(max_iter=100),DecisionTreeClassifier(max_depth=5),RandomForestClassifier(max_depth=5),KNeighborsClassifier(n_neighbors=5)]
# create a int main menu
if __name__ == "__main__":
    while True:
        print("Welcome to weather prediction")
        print("1. Logistic Regression")
        print("2. Support Vector Classifier")
        print("3. Decision Tree Classifier")
        print("4. Random Forest Classifier")
        print("5. K-Nearest Neighbors Classifier")
        print("6. Exit")
        choice = int(input("Enter your choice: "))
        if choice == 1:
            train_model(model[0])
        elif choice == 2:
            train_model(model[1])
        elif choice == 3:
            train_model(model[2])
        elif choice == 4:
            train_model(model[3])
        elif choice == 5:
            train_model(model[4])
        elif choice == 6:
            break
        else:
            print("Invalid choice")